title: Hongyi Ma's Homepage
page-top-title: Hongyi Ma
top-section-bg-text: Life was like a box of chocolate
home-subtitle: Sen Li&ensp;|&ensp;马弘毅
copyright-text: '&copy; Hongyi Ma 2026. All Rights Reserved.'
